### ISSUE TITLE
Add RegQueryInfoKey

### ISSUE THREAD

**Issue by m417z** [simonbuchan/native-reg#11]
Can be useful for getting various information about keys.

**Comment by simonbuchan** [comment]
What would you expect the return type to be? It looks like only actual non-performance related information (that doesn't seem relevant given the current package API) that could be returned is the modified time and the user defined class. Since the current package API doesn't let you set or update the class, and AFAICT it's a weird leftover relic that isn't actually used, I'm not too worried about exposing that. I guess the modified time is potentially useful?

**Comment by m417z** [comment]
For my use case I needed `lpcSubKeys` - the number of subkeys of a given key. I assume that `lpcValues` and, as you said, `lpftLastWriteTime` can also be useful.

**Comment by simonbuchan** [comment]
Interesting, I wouldn't have thought the number of subkeys or values would be valuable except for allocating the array? I guess if you're doing something a like tree-view you would prefer to not need to actually query the subkeys or values, though I'm not sure if there would be much gain after the JS<->C++ overhead, which I understand to be pretty high.

Worth a try at least!

**Comment by m417z** [comment]
> tree-view

Exactly :)

> JS<->C++ overhead

I'm not sure about that, but at least the complexity can be O(#subkeys) and not O(#subkeys-of-subkeys) (by calling `enumKeyNames` for each subkey, the only possible solution with the current API).

**Comment by simonbuchan** [comment]
Well you only need to call `reg.enum*()` once for each key, like you would need to call `reg.queryInfoKey()` once for each key, so it would be only the internal enum overhead, plus whatever GC pressure the extra discarded strings give.

I'm not really against it though, but I don't really want to either get too far away from the underlying API (it is called *native*-reg, afterall) but also it would be weird to include things like the size of the security descriptor if you can't read it. I'll try some things after my break, and see what works out.

**Comment by m417z** [comment]
I was mainly concerned about the internal enum overhead, since the amount of subkeys-of-subkeys can possibly be huge.

In any case, it's just a nice-to-have missing feature I stumbled upon, and I agree it's a bit specific. Let's close it for now, and perhaps revisit it if other users show interest in the future.

**Comment by m417z** [comment]
> I guess if you're doing something a like tree-view

Here's the toy I was working on, in case you were wondering:
https://marketplace.visualstudio.com/items?itemName=m417z.regedit
