### ISSUE TITLE
Add helper functions to convert QWORD to/from BigInt

### ISSUE THREAD

**Issue by m417z** [simonbuchan/native-reg#14]
I think that would be a natural addition to the current set of helper functions.
* Add the following conversion to `parseValue`: `QWORD` -> `BigInt`.
* Make `formatQWORD` receive a `BigInt` instead of a `number`.

**Comment by simonbuchan** [comment]
Since this is still a v0, and BigInt is pretty well supported, this seems reasonable. I'd probably do the existing fixes as a `0.3.*` and do this a a `0.4` just in case though.

**Comment by simonbuchan** [comment]
Sorry it took me so long to get around to this. I don't think my approach has any compatibility issues, so I'm leaving it as `v0.3` for now, but as it's 11:30PM right now, it's only in `@next` tag so far. Let me know if this works for you!

**Comment by m417z** [comment]
Looks like it's working properly, thanks!
