### ISSUE TITLE
Can't read Registry value

### ISSUE THREAD

**Issue by ablito19** [simonbuchan/native-reg#28]
Hello, i made this code but return null .

const reg = require('native-reg');

const key = reg.openKey(
  reg.HKLM,
  'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion',
  reg.Access.ALL_ACCESS);

const version = reg.getValue(key, 'Install', 'CurrentBuild');

 I want to read CurrentBuild from registry in this path 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion'.

**Comment by simonbuchan** [comment]
Do you mean CurrentBuild from SOFTWARE\Microsoft\Windows NT\CurrentVersion\Install? Because that's what it looks like you're reading, so if it is there, I'm not sure. You might instead want queryValue, which doesn't take a subkey.

**Comment by ablito19** [comment]
Can you please post example how read, write registry value, and delete key and subkey instead HKCR but HKCU or HKLM like : HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentBuild

**Comment by simonbuchan** [comment]
No.
