### ISSUE TITLE
BINARY Type

### ISSUE THREAD

**Issue by ablito19** [simonbuchan/native-reg#29]
hello,
How to add BINARY type in registry ?

**Comment by simonbuchan** [comment]
Sorry for the extremely delayed response!

It seems I missed documenting the `setValueRaw()` API, which is a bit embarrassing:

```ts
export function setValueRaw(
  hkey: HKEY,
  valueName: string | null,
  valueType: ValueType,
  data: Buffer,
): void;
```

So you should be able to use:

```ts
reg.setValueRaw(key, "some-value", reg.ValueType.BINARY, data);
```

**Comment by simonbuchan** [comment]
I'll leave this open until I document `setValueRaw()`.

**Comment by simonbuchan** [comment]
Updated the README docs.
