### ISSUE TITLE
This package is just awesome 😍

### ISSUE THREAD

**Issue by LabhanshAgrawal** [simonbuchan/native-reg#6]
Recently in [hyper](https://github.com/zeit/hyper) (https://github.com/zeit/hyper/issues/4190) we needed a module that would read and write to Registry correctly, the one we were using was dealing with unicode incorrectly.
After trying out nearly all the popular packages, nothing seemed to work, and I came upon this package.
And it's the best out there (see my comparison https://github.com/zeit/hyper/issues/4190#issuecomment-586445934)

Thanks for this awesome project, keep up the good work 👍.
P.S. Just wanted to say this so ended up opening this issue, you can close it.

**Comment by simonbuchan** [comment]
Aw, thanks! I had a lot of trouble looking for a package I felt was reliable enough, and I knew C++, so...
