### ISSUE TITLE
"os" in package.json is causing issues in webpack build

### ISSUE THREAD

**Issue by aabuhijleh** [simonbuchan/native-reg#8]
When using this package, my CI is failing due to this error

```
 npm ERR! notsup Unsupported platform for native-reg@0.3.3: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

so I installed `native-reg` as an optional dependency in order to skip it if the OS is not Windows.

Now I get this error when webpack builds the app

```
Module not found: Error: Can't resolve 'native-reg' 
```

I couldn't find a good solution to this issue

To fix this, I'm using my fork right now in which I removed the `os` property from `package.json`

**Comment by simonbuchan** [comment]
What a nightmare! So, webpack actually supports several ways to handle optional dependencies, but it's not actually optional for you.
There are currently a few ways you can get npm to install an os specific package, but most of them seem like bugs. --force will, but will also change a whole bunch of other behavior you don't want. There is an --ignore-engines, but no --ignore-os. There doesn't seem to be any sensible other option here other than just remove the os field which seems basically unsupported: but now npm will try and fail to build it from source on your CI. I would have expected that to have failed the install, but even if it's not, that should also be fixed.

**Comment by aabuhijleh** [comment]
When removing the `os` field the CI doesn't fail :)

**Comment by TheJaredWilcurt** [comment]
If you change your code to

```js
let nativeReg;
if (process.platform === 'win32') {
  nativeReg = require('native-reg');
}

if (nativeReg) {
  // ...
}
```

Would that remove the `Module not found: Error: Can't resolve 'native-reg'` message?

**Comment by aabuhijleh** [comment]
@TheJaredWilcurt If I remember correctly this was not enough for me. I think the build still fails unless I put native-reg as an optional dependency.

I've been doing what you've suggested but with my fork "@aabuhijleh/native-reg" in which I removed "os" from package.json

Nevertheless, this solution isn't pretty especially when you're using typescript where it's really preferred to use the import syntax, not require.

I'm not sure but I think the best solution is to make a no-op version of this module for other platforms besides Windows.

Similar to what [this native module](https://github.com/robinwassen/forcefocus) is doing.
